# Generated by Django 6.0.3 on 2026-03-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paziente_email', models.EmailField(max_length=254, verbose_name='Email del Paziente')),
                ('identificazione_compilatore', models.CharField(choices=[('caregiver', 'Caregiver'), ('paziente', 'Paziente'), ('altro', 'Altro')], default='caregiver', max_length=20, verbose_name='Fonte delle informazioni')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('domanda_1', models.IntegerField(default=0)),
                ('domanda_2', models.IntegerField(default=0)),
                ('domanda_3', models.IntegerField(default=0)),
                ('domanda_4', models.IntegerField(default=0)),
                ('domanda_5', models.IntegerField(default=0)),
                ('domanda_6', models.IntegerField(default=0)),
                ('domanda_7', models.IntegerField(default=0)),
                ('domanda_8', models.IntegerField(default=0)),
                ('domanda_9', models.IntegerField(default=0)),
                ('domanda_10', models.IntegerField(default=0)),
                ('punteggio_totale', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
